In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("C:\\Users\\gajendra singh\\OneDrive\\Desktop\\pandas\\covid_toy.csv")
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [5]:
df['gender'] = lb.fit_transform(df['gender'])

In [6]:
df['cough'] = lb.fit_transform(df['cough'])

In [7]:
df['city'] = lb.fit_transform(df['city'])

In [8]:
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [9]:
df

age  gender  fever  cough  city  has_covid
0    60       1  103.0      0     2          0
1    27       1  100.0      0     1          1
2    42       1  101.0      0     1          0
3    31       0   98.0      0     2          0
4    65       0  101.0      0     3          0
..  ...     ...    ...    ...   ...        ...
95   12       0  104.0      0     0          0
96   51       0  101.0      1     2          1
97   20       0  101.0      0     0          0
98    5       0   98.0      1     3          0
99   10       0   98.0      1     2          1

[100 rows x 6 columns]

In [10]:
from sklearn.model_selection import train_test_split
x = df.drop(columns=['has_covid'], axis=1)
y = df['has_covid']

In [11]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state =42)

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
dt = DecisionTreeClassifier()

In [14]:
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [15]:
y_pred = dt.predict(x_test)

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
accuracy_score(y_test, y_pred)

0.4

#  (1). Attrition
# (2). Placement
# (3). click

In [18]:
df1 = pd.read_csv('Attrition.csv' , usecols = ['Age' , 'Attrition' , 'BusinessTravel' , 'DailyRate' , 'Department' , 'DistanceFromHome' , 'Education'])

In [19]:
df1.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education  
0                 1          2  
1                 8          1  
2                 2          2  
3                 3          4  
4                 2          1

In [20]:
df1['Attrition'] = lb.fit_transform(df1['Attrition'])

In [21]:
df1['BusinessTravel'] = lb.fit_transform(df1['BusinessTravel'])

In [22]:
df1['Department'] = lb.fit_transform(df1['Department'])


In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               1470 non-null   int64
 1   Attrition         1470 non-null   int32
 2   BusinessTravel    1470 non-null   int32
 3   DailyRate         1470 non-null   int64
 4   Department        1470 non-null   int32
 5   DistanceFromHome  1470 non-null   int64
 6   Education         1470 non-null   int64
dtypes: int32(3), int64(4)
memory usage: 63.3 KB


In [24]:
pd.get_dummies(df1, columns= ['BusinessTravel', 'Department'])

Age  Attrition  DailyRate  DistanceFromHome  Education  \
0      41          1       1102                 1          2   
1      49          0        279                 8          1   
2      37          1       1373                 2          2   
3      33          0       1392                 3          4   
4      27          0        591                 2          1   
...   ...        ...        ...               ...        ...   
1465   36          0        884                23          2   
1466   39          0        613                 6          1   
1467   27          0        155                 4          3   
1468   49          0       1023                 2          3   
1469   34          0        628                 8          3   

      BusinessTravel_0  BusinessTravel_1  BusinessTravel_2  Department_0  \
0                    0                 0                 1             0   
1                    0                 1                 0             0   
2                    0                 0                 1             0   
3                    0                 1                 0             0   
4                    0                 0                 1             0   
...                ...               ...               ...           ...   
1465                 0                 1                 0             0   
1466                 0                 0                 1             0   
1467                 0                 0                 1             0   
1468                 0                 1                 0             0   
1469                 0                 0                 1             0   

      Department_1  Department_2  
0                0             1  
1                1             0  
2                1             0  
3                1             0  
4                1             0  
...            ...           ...  
1465             1             0  
1466             1             0  
1467             1             0  
1468             0             1  
1469             1             0  

[1470 rows x 11 columns]

In [25]:
pd.get_dummies(df1, columns= ['BusinessTravel', 'Department'], drop_first = True)

Age  Attrition  DailyRate  DistanceFromHome  Education  \
0      41          1       1102                 1          2   
1      49          0        279                 8          1   
2      37          1       1373                 2          2   
3      33          0       1392                 3          4   
4      27          0        591                 2          1   
...   ...        ...        ...               ...        ...   
1465   36          0        884                23          2   
1466   39          0        613                 6          1   
1467   27          0        155                 4          3   
1468   49          0       1023                 2          3   
1469   34          0        628                 8          3   

      BusinessTravel_1  BusinessTravel_2  Department_1  Department_2  
0                    0                 1             0             1  
1                    1                 0             1             0  
2                    0                 1             1             0  
3                    1                 0             1             0  
4                    0                 1             1             0  
...                ...               ...           ...           ...  
1465                 1                 0             1             0  
1466                 0                 1             1             0  
1467                 0                 1             1             0  
1468                 1                 0             0             1  
1469                 0                 1             1             0  

[1470 rows x 9 columns]

In [26]:
x_train , x_test , y_train , y_test= train_test_split(df1.iloc[:, 0:5] , df1.iloc[: , -3] ,  test_size = 0.1 , random_state=42)

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
ohe = OneHotEncoder(drop = 'first', sparse_output = False, dtype= np.int32)

In [29]:
x_train_new = ohe.fit_transform(x_train[['BusinessTravel' , 'Department']])

In [30]:
x_test_new = ohe.fit_transform(x_test[['BusinessTravel' , 'Department' ]])

In [31]:
x_train_new.shape

(1323, 4)

In [32]:
from sklearn.preprocessing import MinMaxScaler

In [33]:
np.round(x_train.describe(), 1)

Age  Attrition  BusinessTravel  DailyRate  Department
count  1323.0     1323.0          1323.0     1323.0      1323.0
mean     36.9        0.2             1.6      797.5         1.3
std       9.2        0.4             0.7      405.0         0.5
min      18.0        0.0             0.0      102.0         0.0
25%      30.0        0.0             1.0      460.0         1.0
50%      36.0        0.0             2.0      796.0         1.0
75%      43.0        0.0             2.0     1153.5         2.0
max      60.0        1.0             2.0     1498.0         2.0

In [34]:
from sklearn.preprocessing import OrdinalEncoder

In [35]:
mn = MinMaxScaler()

In [36]:
x_train_mn = mn.fit_transform(x_train)

In [37]:
x_test_mn = mn.transform(x_test)

In [38]:
np.round(x_train.describe(),1)

Age  Attrition  BusinessTravel  DailyRate  Department
count  1323.0     1323.0          1323.0     1323.0      1323.0
mean     36.9        0.2             1.6      797.5         1.3
std       9.2        0.4             0.7      405.0         0.5
min      18.0        0.0             0.0      102.0         0.0
25%      30.0        0.0             1.0      460.0         1.0
50%      36.0        0.0             2.0      796.0         1.0
75%      43.0        0.0             2.0     1153.5         2.0
max      60.0        1.0             2.0     1498.0         2.0

In [39]:
x_train_new = pd.DataFrame(x_train_mn , columns=x_train.columns)

In [40]:
np.round(x_train_new.describe(),1)

Age  Attrition  BusinessTravel  DailyRate  Department
count  1323.0     1323.0          1323.0     1323.0      1323.0
mean      0.5        0.2             0.8        0.5         0.6
std       0.2        0.4             0.3        0.3         0.3
min       0.0        0.0             0.0        0.0         0.0
25%       0.3        0.0             0.5        0.3         0.5
50%       0.4        0.0             1.0        0.5         0.5
75%       0.6        0.0             1.0        0.8         1.0
max       1.0        1.0             1.0        1.0         1.0

In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
sc =  StandardScaler()

In [43]:
x_train_scaled  = sc.fit_transform(x_train)
x_test_scaled  = sc.transform(x_test)


In [44]:
np.round(x_train.describe(),1)

Age  Attrition  BusinessTravel  DailyRate  Department
count  1323.0     1323.0          1323.0     1323.0      1323.0
mean     36.9        0.2             1.6      797.5         1.3
std       9.2        0.4             0.7      405.0         0.5
min      18.0        0.0             0.0      102.0         0.0
25%      30.0        0.0             1.0      460.0         1.0
50%      36.0        0.0             2.0      796.0         1.0
75%      43.0        0.0             2.0     1153.5         2.0
max      60.0        1.0             2.0     1498.0         2.0

In [45]:
x_train_new = pd.DataFrame(x_train_scaled , columns=x_train.columns)

In [46]:
np.round(x_train_new.describe(),1)

Age  Attrition  BusinessTravel  DailyRate  Department
count  1323.0     1323.0          1323.0     1323.0      1323.0
mean     -0.0       -0.0             0.0        0.0        -0.0
std       1.0        1.0             1.0        1.0         1.0
min      -2.1       -0.4            -2.4       -1.7        -2.4
25%      -0.8       -0.4            -0.9       -0.8        -0.5
50%      -0.1       -0.4             0.6       -0.0        -0.5
75%       0.7       -0.4             0.6        0.9         1.4
max       2.5        2.3             0.6        1.7         1.4

In [47]:
from sklearn.preprocessing import FunctionTransformer

In [48]:
def Attrition_data(x):
    return np.hstack((x,x*2))

In [49]:
x_transform = Attrition_data(x)

In [50]:
print(x_transform)

[[ 60.   1. 103.   0.   2. 120.   2. 206.   0.   4.]
 [ 27.   1. 100.   0.   1.  54.   2. 200.   0.   2.]
 [ 42.   1. 101.   0.   1.  84.   2. 202.   0.   2.]
 [ 31.   0.  98.   0.   2.  62.   0. 196.   0.   4.]
 [ 65.   0. 101.   0.   3. 130.   0. 202.   0.   6.]
 [ 84.   0.  nan   0.   0. 168.   0.  nan   0.   0.]
 [ 14.   1. 101.   1.   0.  28.   2. 202.   2.   0.]
 [ 20.   0.  nan   1.   3.  40.   0.  nan   2.   6.]
 [ 19.   0. 100.   1.   0.  38.   0. 200.   2.   0.]
 [ 64.   0. 101.   0.   1. 128.   0. 202.   0.   2.]
 [ 75.   0.  nan   0.   1. 150.   0.  nan   0.   2.]
 [ 65.   0.  98.   0.   3. 130.   0. 196.   0.   6.]
 [ 25.   0.  99.   1.   2.  50.   0. 198.   2.   4.]
 [ 64.   1. 102.   0.   0. 128.   2. 204.   0.   0.]
 [ 51.   1. 104.   0.   0. 102.   2. 208.   0.   0.]
 [ 70.   1. 103.   1.   2. 140.   2. 206.   2.   4.]
 [ 69.   0. 103.   0.   2. 138.   0. 206.   0.   4.]
 [ 40.   0.  98.   1.   1.  80.   0. 196.   2.   2.]
 [ 64.   0.  98.   0.   0. 128.   0. 196.   0.

In [51]:
from sklearn.impute import SimpleImputer

In [52]:
si = SimpleImputer()
x_train_Age = si.fit_transform(x_train[['Age']])
x_test_Age =  si.fit_transform(x_test[['Age']])

In [53]:
x_train_Age.shape

(1323, 1)

In [54]:
x_train_Education = x_train.drop(columns = ['Department' , 'DailyRate' , 'Attrition']).values

In [55]:
x_train_Education.shape

(1323, 2)

In [56]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('a' , SimpleImputer() , ['Age']),
    ('b', OrdinalEncoder(categories =[['Research & Development' , 'Sales' , 'Human Resources']]),['Department']),
    ('c', OneHotEncoder(drop = 'first' , sparse_output = False , dtype= np.int32))
],remainder = 'passthrough')

In [57]:
from sklearn.preprocessing import PowerTransformer
import numpy as np

# Sample data (replace this with your data)
data = np.array([[1.0], [2.0], [3.0], [4.0], [5.0]])

# Initialize the PowerTransformer with the method of your choice
# You can choose between 'box-cox' and 'yeo-johnson'
transformer = PowerTransformer(method='yeo-johnson')  # You can also use 'yeo-johnson'

# Fit and transform the data
transformed_data = transformer.fit_transform(data)

# The transformed_data variable now contains the transformed values
print(transformed_data)


[[-1.47297643]
 [-0.66976095]
 [ 0.05534276]
 [ 0.72739861]
 [ 1.35999601]]


In [58]:
transform = PowerTransformer(method = 'yeo-johnson')


In [59]:
transformed_data = transformer.fit_transform(df)

In [60]:
print(transformed_data)

[[ 0.68533483  1.19959343  1.05343062 -0.78288136  0.66998777 -0.90453403]
 [-0.60147646  1.19959343 -0.38343254 -0.78288136 -0.20707493  1.1055416 ]
 [ 0.03079622  1.19959343  0.11277948 -0.78288136 -0.20707493 -0.90453403]
 [-0.4222769  -0.83361577 -1.43175311 -0.78288136  0.66998777 -0.90453403]
 [ 0.85331377 -0.83361577  0.11277948 -0.78288136  1.42168147 -0.90453403]
 [ 1.45139893 -0.83361577         nan -0.78288136 -1.3210288   1.1055416 ]
 [-1.26853391  1.19959343  0.11277948  1.27733275 -1.3210288  -0.90453403]
 [-0.94088479 -0.83361577         nan  1.27733275  1.42168147  1.1055416 ]
 [-0.99271031 -0.83361577 -0.38343254  1.27733275 -1.3210288  -0.90453403]
 [ 0.82011951 -0.83361577  0.11277948 -0.78288136 -0.20707493 -0.90453403]
 [ 1.17528958 -0.83361577         nan -0.78288136 -0.20707493 -0.90453403]
 [ 0.85331377 -0.83361577 -1.43175311 -0.78288136  1.42168147  1.1055416 ]
 [-0.69474512 -0.83361577 -0.89798617  1.27733275  0.66998777 -0.90453403]
 [ 0.82011951  1.19959343

In [63]:
df2 = pd.read_csv("C:\\Users\\gajendra singh\\OneDrive\\Desktop\\pandas\\placement.csv")

In [64]:
df2.head()

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [65]:
sc = StandardScaler()

In [66]:
x_train , x_test , y_train , y_test= train_test_split(df2.iloc[:, 0:5] , df2.iloc[: , -3] ,  test_size = 0.1 , random_state=42)

In [67]:
x_train_scaled  = sc.fit_transform(x_train)
x_test_scaled  = sc.transform(x_test)


In [68]:
np.round(x_train.describe(),1)

cgpa  resume_score  placed
count  90.0          90.0    90.0
mean    6.9           7.0     0.5
std     1.1           1.0     0.5
min     5.3           5.0     0.0
25%     5.9           6.3     0.0
50%     6.6           7.1     0.0
75%     8.1           7.6     1.0
max     9.4           9.1     1.0

In [69]:
x_train_new = pd.DataFrame(x_train_scaled , columns=x_train.columns)

In [70]:
np.round(x_train_new.describe(),1)

cgpa  resume_score  placed
count  90.0          90.0    90.0
mean    0.0           0.0     0.0
std     1.0           1.0     1.0
min    -1.5          -2.0    -1.0
25%    -0.9          -0.7    -1.0
50%    -0.3           0.1    -1.0
75%     1.0           0.7     1.0
max     2.2           2.1     1.0

In [71]:
mn =  MinMaxScaler()

In [72]:
x_train_mn = mn.fit_transform(x_train)

In [73]:
x_test_mn = mn.transform(x_test)

In [74]:
np.round(x_train.describe(),1)

cgpa  resume_score  placed
count  90.0          90.0    90.0
mean    6.9           7.0     0.5
std     1.1           1.0     0.5
min     5.3           5.0     0.0
25%     5.9           6.3     0.0
50%     6.6           7.1     0.0
75%     8.1           7.6     1.0
max     9.4           9.1     1.0

In [75]:
x_train_new = pd.DataFrame(x_train_mn , columns=x_train.columns)

In [76]:
np.round(x_train_new.describe(),1)

cgpa  resume_score  placed
count  90.0          90.0    90.0
mean    0.4           0.5     0.5
std     0.3           0.2     0.5
min     0.0           0.0     0.0
25%     0.2           0.3     0.0
50%     0.3           0.5     0.0
75%     0.7           0.7     1.0
max     1.0           1.0     1.0

In [77]:
si = SimpleImputer()
x_train_cgpa = si.fit_transform(x_train[['cgpa']])
x_test_cgpa =  si.fit_transform(x_test[['cgpa']])

In [78]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('a' , SimpleImputer() , ['cgpa']),
    ('c', OneHotEncoder(drop = 'first' , sparse_output = False , dtype= np.int32))
],remainder = 'passthrough')

In [79]:
data_transform = PowerTransformer(method = 'yeo-johnson')


In [80]:
transformed_data = data_transform.fit_transform(df2)


In [81]:
transformed_data

array([[ 1.08394218, -0.43444977,  1.        ],
       [-0.63344948, -1.77389637, -1.        ],
       [ 1.17031692,  2.02431148,  1.        ],
       [ 0.09002554,  0.33594683,  1.        ],
       [ 0.63362792,  0.36712563,  1.        ],
       [ 1.47997289, -0.76769373,  1.        ],
       [-1.6973823 ,  0.14944982, -1.        ],
       [-0.218303  , -0.66709276, -1.        ],
       [-0.46825279, -0.24096413, -1.        ],
       [ 0.76385142,  0.18046372,  1.        ],
       [-0.62220971, -0.60657178, -1.        ],
       [-1.55384053, -0.41413788, -1.        ],
       [-0.72457253,  0.06688195, -1.        ],
       [ 1.31703051, -1.85120779,  1.        ],
       [ 0.62579668, -0.70737338,  1.        ],
       [ 1.54366528, -1.02766905,  1.        ],
       [ 1.01571521,  0.7223699 ,  1.        ],
       [ 0.85258396,  1.86202781,  1.        ],
       [-0.90140883, -1.07739758, -1.        ],
       [-0.03199323,  1.21900685,  1.        ],
       [-1.07389153,  1.16587288, -1.   

In [82]:
from sklearn.preprocessing import FunctionTransformer

In [83]:
def placement_data(x):
    return np.vstack((x,x*2))

In [84]:
x_transformed = placement_data(x)

In [85]:
print(x_transformed)

[[ 60.   1. 103.   0.   2.]
 [ 27.   1. 100.   0.   1.]
 [ 42.   1. 101.   0.   1.]
 [ 31.   0.  98.   0.   2.]
 [ 65.   0. 101.   0.   3.]
 [ 84.   0.  nan   0.   0.]
 [ 14.   1. 101.   1.   0.]
 [ 20.   0.  nan   1.   3.]
 [ 19.   0. 100.   1.   0.]
 [ 64.   0. 101.   0.   1.]
 [ 75.   0.  nan   0.   1.]
 [ 65.   0.  98.   0.   3.]
 [ 25.   0.  99.   1.   2.]
 [ 64.   1. 102.   0.   0.]
 [ 51.   1. 104.   0.   0.]
 [ 70.   1. 103.   1.   2.]
 [ 69.   0. 103.   0.   2.]
 [ 40.   0.  98.   1.   1.]
 [ 64.   0.  98.   0.   0.]
 [ 42.   0.  nan   1.   0.]
 [ 12.   1.  98.   1.   0.]
 [ 73.   1.  98.   0.   0.]
 [ 71.   0.  98.   1.   2.]
 [ 80.   0.  98.   0.   1.]
 [ 13.   0. 100.   1.   2.]
 [ 23.   1.  nan   0.   3.]
 [ 19.   0. 100.   0.   2.]
 [ 33.   0. 102.   1.   1.]
 [ 16.   1. 104.   0.   2.]
 [ 34.   0.  nan   1.   3.]
 [ 15.   1. 101.   0.   1.]
 [ 83.   1. 103.   0.   2.]
 [ 34.   0. 101.   1.   1.]
 [ 26.   0.  98.   0.   2.]
 [ 74.   1. 102.   0.   3.]
 [ 82.   0. 102.   1

In [86]:
x_transformed

array([[ 60.,   1., 103.,   0.,   2.],
       [ 27.,   1., 100.,   0.,   1.],
       [ 42.,   1., 101.,   0.,   1.],
       [ 31.,   0.,  98.,   0.,   2.],
       [ 65.,   0., 101.,   0.,   3.],
       [ 84.,   0.,  nan,   0.,   0.],
       [ 14.,   1., 101.,   1.,   0.],
       [ 20.,   0.,  nan,   1.,   3.],
       [ 19.,   0., 100.,   1.,   0.],
       [ 64.,   0., 101.,   0.,   1.],
       [ 75.,   0.,  nan,   0.,   1.],
       [ 65.,   0.,  98.,   0.,   3.],
       [ 25.,   0.,  99.,   1.,   2.],
       [ 64.,   1., 102.,   0.,   0.],
       [ 51.,   1., 104.,   0.,   0.],
       [ 70.,   1., 103.,   1.,   2.],
       [ 69.,   0., 103.,   0.,   2.],
       [ 40.,   0.,  98.,   1.,   1.],
       [ 64.,   0.,  98.,   0.,   0.],
       [ 42.,   0.,  nan,   1.,   0.],
       [ 12.,   1.,  98.,   1.,   0.],
       [ 73.,   1.,  98.,   0.,   0.],
       [ 71.,   0.,  98.,   1.,   2.],
       [ 80.,   0.,  98.,   0.,   1.],
       [ 13.,   0., 100.,   1.,   2.],
       [ 23.,   1.,  nan,

In [89]:
x_test

cgpa  resume_score  placed
83  7.60          8.08       1
53  6.00          7.16       0
70  7.12          7.41       1
45  8.10          5.44       1
44  5.47          5.92       0
39  7.50          6.19       1
22  6.16          5.77       0
80  7.83          7.70       1
10  6.18          6.35       0
0   8.14          6.52       1